# Generated by Django 5.2.4 on 2025-07-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-release_date']},
        ),
    ]
