# Generated by Django 5.2.4 on 2025-07-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_content_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='genre',
            new_name='genres',
        ),
    ]
