# Generated by Django 5.2.4 on 2025-08-02 10:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_watechhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WatechHistory',
            new_name='WatchedHistory',
        ),
    ]
