# Generated by Django 5.2.4 on 2025-08-02 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_rename_watechhistory_watchedhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchedhistory',
            old_name='wateched_at',
            new_name='watched_at',
        ),
        migrations.AlterField(
            model_name='watchedhistory',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_history', to='movie.content'),
        ),
    ]
