# Generated by Django 5.2.4 on 2025-08-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_rename_wateched_at_watchedhistory_watched_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedhistory',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
